---
- name: generating sudo user password
  set_fact:
    sudo_password: "{{ password }}"
  no_log: true
  run_once: true
  delegate_to: "localhost"

#- name: writing sudo user password to vars
#  lineinfile:
#    insertafter: EOF
#    path: group_vars/linode/vars
#    line: | 
#      password: {{ password }}

# sudo user and pass in run script

- name: set sudo user
  user:
        name: "{{ username }}"
        shell: /bin/bash
        groups: sudo
        password: "{{ sudo_password | password_hash('sha512') }}"
        update_password: on_create
        expires: -1
        append: yes
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        state: present